from contextlib import contextmanager
from datetime import date, datetime
from typing import Optional

import psycopg2
import psycopg2.extras

import config
from clients.embeddings_client import embed_text

# Formats OCR might hand back in invoice_date, tried in order.
_DATE_FORMATS = ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y", "%d %b %Y", "%B %d, %Y")


def _insert_outbox(cur, queue_name: str, payload: dict) -> None:
    """Transactional outbox: called with the same cursor (and therefore the
    same not-yet-committed transaction) as the business write it's about,
    so a later SQS publish failure just means the relay worker
    (workers/outbox_relay_worker.py) retries it on its next pass, instead
    of the message being silently lost."""
    cur.execute(
        "INSERT INTO queue_outbox (queue_name, payload) VALUES (%s, %s)",
        (queue_name, psycopg2.extras.Json(payload)),
    )


def parse_invoice_date(raw: Optional[str]) -> Optional[date]:
    if not raw:
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(raw.strip(), fmt).date()
        except ValueError:
            continue
    return None


@contextmanager
def get_connection():
    conn = psycopg2.connect(config.DB_URL)
    try:
        yield conn
    finally:
        conn.close()


def fetch_unprocessed_invoice_documents(conn):
    """document rows for INVOICE work items that have no work_execution row yet."""
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT d.work_id, d.document_id, d.document_link
            FROM document d
            JOIN work_item wi ON wi.work_id = d.work_id
            LEFT JOIN work_execution we ON we.work_id = d.work_id
            WHERE wi.process_type = 'INVOICE'
              AND we.work_id IS NULL
            """
        )
        return cur.fetchall()


def claim_work_item(conn, work_id: str) -> bool:
    """Atomically flip a work item to EXTRACTION_STARTED.

    Returns True if this call created the row (i.e. won the claim), False if
    a work_execution row already existed (another worker got there first).
    Safe to call even with multiple concurrent pollers.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO work_execution (work_id, status)
            VALUES (%s, 'EXTRACTION_STARTED')
            ON CONFLICT (work_id) DO NOTHING
            RETURNING work_id
            """,
            (work_id,),
        )
        won = cur.fetchone() is not None
        if won:
            cur.execute(
                "INSERT INTO work_execution_log (work_id, status) VALUES (%s, 'EXTRACTION_STARTED')",
                (work_id,),
            )
    conn.commit()
    return won


def mark_status(conn, work_id: str, status: str, detail: Optional[str] = None):
    with conn.cursor() as cur:
        cur.execute(
            """
            UPSERT INTO work_execution (work_id, status, updated_at)
            VALUES (%s, %s, now())
            """,
            (work_id, status),
        )
        cur.execute(
            "INSERT INTO work_execution_log (work_id, status, detail) VALUES (%s, %s, %s)",
            (work_id, status, detail),
        )
    conn.commit()


def insert_email_scan(conn, count_of_email: int) -> str:
    """One row per ingestion run. Written once the run's final count of
    qualifying (invoice/document) emails is known -- i.e. after the whole
    inbox scan, not before -- since email.scan_id is NOT NULL and every
    email row in the scan needs this scan_id to already exist."""
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO email_scan (count_of_email) VALUES (%s) RETURNING scan_id",
            (count_of_email,),
        )
        scan_id = cur.fetchone()[0]
    conn.commit()
    return scan_id


def insert_email(
    conn, scan_id: str, email_from: str, email_subject: str, email_content: str
) -> str:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO email (scan_id, email_from, email_subject, email_content)
            VALUES (%s, %s, %s, %s)
            RETURNING email_id
            """,
            (scan_id, email_from, email_subject, email_content),
        )
        email_id = cur.fetchone()[0]
    conn.commit()
    return email_id


def insert_work_item_and_document(
    conn, work_id: str, email_id: str, document_link: str, process_type: str = "INVOICE"
) -> None:
    """Insert the work_item and its 1:1 document row together, in one
    transaction. work_id is generated by the caller (uuid4) before this is
    called, because the S3 upload that produces document_link needs a
    work_id to key on and must happen first -- call this only after that
    upload has already succeeded, so a failure here never leaves an
    orphaned work_item with no matching document."""
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO work_item (work_id, email_id, process_type) VALUES (%s, %s, %s)",
            (work_id, email_id, process_type),
        )
        cur.execute(
            "INSERT INTO document (work_id, document_link) VALUES (%s, %s)",
            (work_id, document_link),
        )
        _insert_outbox(cur, "invoice", {"work_id": work_id, "document_link": document_link})
    conn.commit()


def find_invoice_by_work_id(conn, work_id: str) -> Optional[str]:
    """Confirms `work_id` (extracted from an incoming email that's
    referencing a prior invoice) actually corresponds to an
    already-validated invoice. helpdesk rows require a non-null
    invoice_work_id by schema design -- a referenced work_id that doesn't
    exist yet, or exists but was never an invoice, can't be recorded as a
    helpdesk item. Returns work_id itself (unchanged) if valid, else None
    -- same Optional[str] shape as the other find_* lookups, so callers
    don't need to special-case this one."""
    with conn.cursor() as cur:
        cur.execute("SELECT invoice_work_id FROM invoice WHERE invoice_work_id = %s", (work_id,))
        row = cur.fetchone()
        return row[0] if row else None


def fetch_sender_for_work_id(conn, work_id: str) -> Optional[dict]:
    """The original sender/subject of the email that spawned this work_id,
    so a status update (completed / failed / declined-as-duplicate) can be
    emailed back to whoever sent it in the first place."""
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT e.email_from, e.email_subject
            FROM work_item wi
            JOIN email e ON e.email_id = wi.email_id
            WHERE wi.work_id = %s
            """,
            (work_id,),
        )
        return cur.fetchone()


def insert_work_item_and_helpdesk(conn, work_id: str, email_id: str, invoice_work_id: str) -> None:
    """Insert the work_item (process_type=HELPDESK) and its 1:1 helpdesk
    row together, in one transaction -- mirrors insert_work_item_and_document
    for the invoice path."""
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO work_item (work_id, email_id, process_type) VALUES (%s, %s, %s)",
            (work_id, email_id, "HELPDESK"),
        )
        cur.execute(
            "INSERT INTO helpdesk (helpdesk_work_id, invoice_work_id) VALUES (%s, %s)",
            (work_id, invoice_work_id),
        )
        _insert_outbox(cur, "helpdesk", {"work_id": work_id, "invoice_work_id": invoice_work_id})
    conn.commit()


def fetch_helpdesk_query(conn, helpdesk_work_id: str) -> Optional[dict]:
    """The sender/subject/body of the original query email plus the
    invoice_work_id it's about, for a HELPDESK work item -- everything
    services/helpdesk_query_service.py needs to build a prompt for the LLM
    and address the reply."""
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT e.email_from, e.email_subject, e.email_content, h.invoice_work_id
            FROM helpdesk h
            JOIN work_item wi ON wi.work_id = h.helpdesk_work_id
            JOIN email e ON e.email_id = wi.email_id
            WHERE h.helpdesk_work_id = %s
            """,
            (helpdesk_work_id,),
        )
        return cur.fetchone()


def insert_invoice_source_and_line_items(conn, work_id: str, invoice_data):
    """Insert the raw (pre-validation) OCR output into invoice_source /
    line_item_source, as-is -- nulls stay null, no placeholder defaults.
    This is what duplicate/PO validation for later invoices is checked
    against, so it has to reflect exactly what the model returned."""
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO invoice_source (
                invoice_work_id, invoice_number, invoice_date,
                vendor_name, total_amount, invoice_currency, purchase_order
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            (
                work_id,
                invoice_data.invoice_no,
                parse_invoice_date(invoice_data.invoice_date),
                invoice_data.customer_name,
                invoice_data.invoice_amount,
                invoice_data.currency,
                invoice_data.purchase_order,
            ),
        )

        for idx, li in enumerate(invoice_data.line_items or [], start=1):
            cur.execute(
                """
                INSERT INTO line_item_source (
                    invoice_work_id, line_number, description,
                    quantity, unit_price, line_amount, description_embedding
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    work_id, idx, li.description, li.quantity, li.unit_price, li.amount,
                    embed_text(li.description),
                ),
            )
    conn.commit()


def find_duplicate_invoice(
    conn,
    invoice_number: str,
    purchase_order: Optional[str],
    invoice_date,
    total_amount,
    invoice_currency: str,
    exclude_work_id: str,
) -> Optional[str]:
    """5-field match (invoice_number, purchase_order, invoice_date,
    total_amount, invoice_currency) against already-validated invoices.
    Returns the existing invoice_work_id if this invoice has already been
    processed, else None. `IS NOT DISTINCT FROM` is used for the nullable
    fields so two invoices that both omit a PO/date still count as a
    match on that field rather than never matching (NULL = NULL is
    normally unknown, not true). total_amount is matched within a cent
    rather than by exact equality -- re-running OCR on the identical PDF
    has been observed to return e.g. 476.698 one time and 476.70 (stored,
    already-rounded) the next, and exact `=` against a DECIMAL(18,2)
    column silently misses that as a match."""
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT invoice_work_id FROM invoice
            WHERE invoice_number = %s
              AND purchase_order IS NOT DISTINCT FROM %s
              AND invoice_date IS NOT DISTINCT FROM %s
              AND total_amount BETWEEN %s - 0.01 AND %s + 0.01
              AND invoice_currency = %s
              AND invoice_work_id != %s
            LIMIT 1
            """,
            (
                invoice_number, purchase_order, invoice_date,
                total_amount, total_amount, invoice_currency, exclude_work_id,
            ),
        )
        row = cur.fetchone()
        return row[0] if row else None


def find_po_in_source(conn, purchase_order: str, exclude_work_id: str) -> Optional[str]:
    """A PO is treated as validated if it appears on some other, earlier
    invoice_source row -- i.e. we've genuinely seen this PO before on a
    document that came through the pipeline. Returns that row's
    invoice_work_id (the earliest match) so its line items can be pulled
    for comparison, or None if the PO has never been seen."""
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT invoice_work_id FROM invoice_source
            WHERE purchase_order = %s AND invoice_work_id != %s
            ORDER BY created_at ASC
            LIMIT 1
            """,
            (purchase_order, exclude_work_id),
        )
        row = cur.fetchone()
        return row[0] if row else None


def fetch_line_item_comparison(conn, current_work_id: str, source_work_id: str):
    """Line-by-line comparison of two invoices' line_item_source rows,
    joined on line_number. A FULL OUTER JOIN so a line present on only one
    side (i.e. the two invoices have a different number of lines) shows up
    as a row with NULLs on the other side, rather than silently being left
    out. description_distance is computed by CockroachDB itself via the
    <-> operator over the stored embeddings -- there are only ever a
    handful of rows for one PO, so this needs no vector index, just an
    exact distance calculation."""
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT
                curr.line_number AS curr_line_number,
                src.line_number AS src_line_number,
                curr.quantity AS curr_quantity, curr.unit_price AS curr_unit_price,
                curr.line_amount AS curr_line_amount,
                src.quantity AS src_quantity, src.unit_price AS src_unit_price,
                src.line_amount AS src_line_amount,
                curr.description_embedding <-> src.description_embedding AS description_distance
            FROM
                (SELECT * FROM line_item_source WHERE invoice_work_id = %s) curr
            FULL OUTER JOIN
                (SELECT * FROM line_item_source WHERE invoice_work_id = %s) src
            ON curr.line_number = src.line_number
            ORDER BY COALESCE(curr.line_number, src.line_number)
            """,
            (current_work_id, source_work_id),
        )
        return cur.fetchall()


def find_similar_vendor(conn, vendor_embedding: Optional[str], exclude_work_id: str) -> Optional[dict]:
    """Nearest existing vendor by embedding distance, via the vector index
    on invoice.vendor_embedding -- an ANN search over the whole table,
    unlike the per-PO line-item comparison above. Returns the nearest
    work_id/vendor_name/distance regardless of how close it is; the caller
    decides what distance counts as "the same vendor". None if there's no
    embedding to search with, or the invoice table is empty."""
    if vendor_embedding is None:
        return None

    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT invoice_work_id, vendor_name, vendor_embedding <-> %s AS distance
            FROM invoice
            WHERE invoice_work_id != %s AND vendor_embedding IS NOT NULL
            ORDER BY vendor_embedding <-> %s
            LIMIT 1
            """,
            (vendor_embedding, exclude_work_id, vendor_embedding),
        )
        return cur.fetchone()


def append_log(conn, work_id: str, status: str, detail: Optional[str] = None) -> None:
    """Append a breadcrumb to work_execution_log without touching the
    current-status row in work_execution -- for intermediate steps (PO
    validation outcome, duplicate match reference) that are worth
    recording but shouldn't overwrite the pipeline's current status."""
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO work_execution_log (work_id, status, detail) VALUES (%s, %s, %s)",
            (work_id, status, detail),
        )
    conn.commit()


def insert_invoice_and_line_items(conn, work_id: str, invoice_data, vendor_embedding: Optional[str] = None):
    """Insert the (placeholder, until real invoice-population logic lands)
    invoice row plus its line_items, from an ocr.Invoice instance.
    vendor_embedding is computed once by the caller (invoice_extraction_service),
    since it's also needed there for the vendor-similarity lookup before
    this insert happens -- no reason to call the embedding model twice."""
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO invoice (
                invoice_work_id, invoice_number, invoice_date,
                vendor_name, total_amount, invoice_currency, purchase_order,
                vendor_embedding
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                work_id,
                invoice_data.invoice_no or "UNKNOWN",
                parse_invoice_date(invoice_data.invoice_date),
                invoice_data.customer_name or "UNKNOWN",
                invoice_data.invoice_amount or 0,
                invoice_data.currency or "USD",
                invoice_data.purchase_order,
                vendor_embedding,
            ),
        )

        for idx, li in enumerate(invoice_data.line_items or [], start=1):
            cur.execute(
                """
                INSERT INTO line_item (
                    invoice_work_id, line_number, description,
                    quantity, unit_price, line_amount
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (work_id, idx, li.description, li.quantity, li.unit_price, li.amount or 0),
            )
    conn.commit()


def insert_outbox_only(conn, queue_name: str, payload: dict) -> None:
    """For messages with no corresponding work_item -- e.g. an email that
    didn't classify as INVOICE or HELPDESK at all, routed to the 'other'
    queue purely for visibility instead of being silently dropped."""
    with conn.cursor() as cur:
        _insert_outbox(cur, queue_name, payload)
    conn.commit()


def fetch_unpublished_outbox_messages(conn, limit: int = 50):
    """Rows the relay worker hasn't successfully published to SQS yet."""
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            "SELECT id, queue_name, payload FROM queue_outbox WHERE NOT published ORDER BY created_at LIMIT %s",
            (limit,),
        )
        return cur.fetchall()


def mark_outbox_published(conn, outbox_id: str) -> None:
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE queue_outbox SET published = true, published_at = now() WHERE id = %s",
            (outbox_id,),
        )
    conn.commit()
